### PR TITLE
Release GetMandateConstraints and RevokeMandate

### PR DESCRIPTION
**Pull request by ubunoir**
Had to introduce some changes as well in the base ApiClient class:

- enabled signing requests which have no request content (e.g. revoke mandate)
- added overloaded PostAsync methods which can be used when no response content is expected (204 NoContent response, e.g. revoke mandate)

### CODE REVIEW

**Review by tl-mauro-franchi — APPROVED** [review]
LGTM

**Comment by tl-mauro-franchi** [comment]
@ubunoir could you please share the screenshot of the tests from your local machine against our sandbox?

**Comment by ubunoir** [comment]
Locally I have all tests passed:

image

Here I can see that `System.ComponentModel.DataAnnotations.ValidationException : Your client id is required` error everywhere, not sure why?

**Comment by tl-mauro-franchi** [comment]
> Here I can see that `System.ComponentModel.DataAnnotations.ValidationException : Your client id is required` error everywhere, not sure why?

Unfortunately that is because the GH action that runs the cake script is not able to get the settings from your fork for some odd reason, despite the actions have been configured to work with forks as well 🤷🏻‍♂️
We will try to fix it but for now, please always remember to put a screenshot of the result of the tests from your local machine (it would be good if you can show at least the new added tests as well).

**Review by tl-mauro-franchi — APPROVED** [review]

**Pull request merged**
