### PR TITLE
Release StartAuthorizationFlow, SubmitProviderSelection, GetConfirmationOfFunds Mandates

### PR DESCRIPTION
**Pull request by mohammedmiah99**

### CODE REVIEW

**Review by Couper4 — CHANGES_REQUESTED** [review]
The following files have some `using`s that can be removed:
```
src/TrueLayer/Models/AuthorisationFlowResponse.cs
src/TrueLayer/Models/Configuration.cs
src/TrueLayer/Models/RedirectStatus.cs
src/TrueLayer/Models/StartAuthorizationFlowRequest.cs
src/TrueLayer/Models/SubmitProviderSelectionRequest.cs
```

**Review by Couper4 — COMMENTED** [review]
Not strictly related to this PR but worth keeping in mind for future PRs: I think it would be better if we move the classes from `TrueLayer.Models` to `TrueLayer.Mandates.Model` because those are used only for mandates.

Let me know what do you think.

**Comment by mohammedmiah99** [comment]
> Not strictly related to this PR but worth keeping in mind for future PRs: I think it would be better if we move the classes from `TrueLayer.Models` to `TrueLayer.Mandates.Model` because those are used only for mandates.
> 
> Let me know what do you think.

@Couper4 I think @Ryan-Palmer mentioned this when creating the models, see slack chat - https://tandem.slack.com/archives/CL1A5MLBZ/p1689334796944919 I think we just followed the implementation in the Java SDK in having it in a common space in case it was used in other places such as payments.

**Comment by mohammedmiah99** [comment]
Unit tests pass
image

**Review by tl-mauro-franchi — APPROVED** [review]
LGTM

**Comment by Couper4** [comment]
> > Not strictly related to this PR but worth keeping in mind for future PRs: I think it would be better if we move the classes from `TrueLayer.Models` to `TrueLayer.Mandates.Model` because those are used only for mandates.
> > Let me know what do you think.
> 
> @Couper4 I think @Ryan-Palmer mentioned this when creating the models, see slack chat - https://tandem.slack.com/archives/CL1A5MLBZ/p1689334796944919 I think we just followed the implementation in the Java SDK in having it in a common space in case it was used in other places such as payments.

You're right, the Java SDK is doing the same thing, that's completely fine.

**Review by Couper4 — APPROVED** [review]

**Pull request merged**
